apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: cluster-service
  name: cluster-service
spec:
  ports:
  - name: tcp
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: cluster-service
  type: ClusterIP
status:
  loadBalancer: {}
