apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nodeport-service
  name: nodeport-service
spec:
  ports:
  - name: tcp
    port: 8080
    protocol: TCP
    targetPort: 80
    nodePort: 31000
  selector:
    app: nodeport-service
  type: NodePort
status:
  loadBalancer: {}
